baseURL = 'http://example.org/'
languageCode = 'zh-cn'
defaultContentLanguage = 'zh-cn'
title = 'My New Hugo Site'
theme = 'hello-friend'

[params]
  contentTypeName = "post"
  defaultTheme = "light"

  showMenuItems = 2

  toc = true

[languages]
  [languages.zh-cn]
    title = "HigherSY 的世界"
    subtitle = "生活 / 技术 / 碎碎念"

